name: Build & Release WP Plugin

# Fire whenever you push a tag matching vMAJOR.MINOR.PATCH
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Read version from tag
        id: vars
        run: |
          # strip leading "v"
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Patch plugin PHP version
        run: |
          sed -i \
            -e "s/^ \* Version: .*/ * Version: ${{ steps.vars.outputs.VERSION }}/" \
            wordpress/agentman-chat-widget.php
          sed -i \
            -e "s/define( 'AGENTMAN_CHAT_WIDGET_VERSION', .*/define( 'AGENTMAN_CHAT_WIDGET_VERSION', '${{ steps.vars.outputs.VERSION }}' );/" \
            wordpress/agentman-chat-widget.php

      - name: Install & build front-end
        run: |
          npm ci
          npm run build

      - name: Build WP plugin ZIP
        run: |
          zip -r agentman-chat-widget-${{ steps.vars.outputs.VERSION }}.zip wordpress

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZIP to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./agentman-chat-widget-${{ steps.vars.outputs.VERSION }}.zip
          asset_name: agentman-chat-widget-${{ steps.vars.outputs.VERSION }}.zip
          asset_content_type: application/zip